-- >>> from former migration 957 (down; regenerated by RUYI-359 Phase 2R)
--
-- The original 957 down predated this consolidation and restored the
-- proposal table WITHOUT the transfer_state column (added by the former
-- 950, now part of 911_knowledge) and WITHOUT the two proposal indexes
-- (built by the former 943/944/955, now part of 910_proposal) — the known
-- RUYI-360 rollback defect. The rollback ladder now descends
-- 913_skill -> 911_knowledge -> 910_proposal, so this restore must
-- reproduce the exact pre-957 proposal shape (transfer_state and both
-- indexes included) for those later rollbacks to consume. Rows dropped by
-- the former 957 remain unrecoverable by design (dev-stage experiment
-- data, per the original up migration).
CREATE TABLE proposal (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id UUID NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('prompt_revision', 'project_cognition', 'lesson', 'pitfall', 'skill')),
    status TEXT NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'needs_revision', 'adopted', 'rejected', 'archived')),
    title TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
    prophecy JSONB NOT NULL,
    generation_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    adoption_snapshot JSONB,
    verification JSONB,
    audit_log JSONB NOT NULL DEFAULT '[]'::jsonb,
    transfer_error TEXT NOT NULL DEFAULT '',
    created_by_type TEXT NOT NULL DEFAULT 'member' CHECK (created_by_type IN ('member', 'agent', 'system')),
    created_by_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE proposal IS 'Self-evolution proposals: falsifiable prophecy fixed at creation (B1), adoption and verification recorded separately (B2), rejected proposals retained without version links (B3).';

-- Restore of the transfer_state column added by the former 950.
ALTER TABLE proposal ADD COLUMN transfer_state TEXT NOT NULL DEFAULT '';

-- Restore of the index built by the former 944.
CREATE INDEX idx_proposal_workspace_status
ON proposal (workspace_id, status);

-- Restore of the index built by the former 955.
CREATE UNIQUE INDEX uidx_proposal_system_dir
ON proposal ((generation_snapshot->>'knowledge_dir_id'))
WHERE generation_snapshot ? 'knowledge_dir_id';

ALTER TABLE skill_version DROP CONSTRAINT IF EXISTS skill_version_source_check;
ALTER TABLE skill_version ADD CONSTRAINT skill_version_source_check
    CHECK (source IN ('create', 'proposal', 'revision', 'edit', 'restore'));
ALTER TABLE skill_version ADD COLUMN IF NOT EXISTS source_proposal_id UUID;
