-- Down for 918_channel_capability_state: drop the probe-state table. It is
-- pure derived diagnostics (regenerated by the next recheck), so dropping it
-- loses nothing that cannot be recomputed.
DROP TABLE IF EXISTS channel_capability_state;
